class ElementIDS:
    REQUEST_ID = "ctl00_Menu1_linkEligibilityRequest"
    RESPONSE_ID = "ctl00_Menu1_linkEligibilityResponse"
    INPUT_CLIENT_ID = "ctl00_ContentPlaceHolder1_textBoxClientID"
    CLIENTNAME_ID = "ctl00_ContentPlaceHolder1_labelClientName"
    ADDRESS_ID = "ctl00_ContentPlaceHolder1_labelClientAddress1"
    CITY_STATE_ZIP_ID = "ctl00_ContentPlaceHolder1_labelClientCityStateZip"
    DATE_OF_BIRTH_ID = "ctl00_ContentPlaceHolder1_labelClientDOB"
    CLIENT_GENDER_ID = "ctl00_ContentPlaceHolder1_labelClientGender"
    SUBMIT_BUTTON_ID = "ctl00_ContentPlaceHolder1_buttonSubmit"
